base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('starter/', views.StarterView.as_view(), name='starter'),
    path('hizmetlerimiz/<slug>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path('iletisim/', views.ContactView, name='contact'),
    path('subscriber/', views.SubscriberView, name='subscriber'),
    path('fiyatlandirma/', views.PricingView.as_view(), name='pricing'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_ckeditor_5.views import upload_file
from base.models import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path("ckeditor5/image_upload/", upload_file, name="ckeditor_upload_file"),
    path(r"images-handler/", include("galleryfield.urls")),
    path('', include('base.urls')),
    path('', include('post.urls')),
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


try:
    site = Home.objects.latest('created')
    admin.site.site_title = site.name
    admin.site.site_header = site.name
    admin.site.index_title = site.name
    admin.site.name = site.name
except:
    pass

post/urls.py
from django.urls import path
from post import views

app_name = 'post'

urlpatterns = [
    path('blog/', views.ArticleListView.as_view(), name='blog'),
    path('blog/<pk>/<slug>/', views.ArticleDetailView.as_view(), name='blog_details'),
    path('blog/<tags>-etiketi/', views.ArticleTagsListView.as_view(), name='tags_list'),
    path('blog/<title>-kategorisi/', views.ArticleCategoryListView.as_view(), name='category_list'),
    path('blog/<user>-Makaleleri/', views.ArticleAuthorListView.as_view(), name='author_list'),
    path('report-comment/<pk>/', views.comment_report_view, name='comment_report'),
    path('blog-<int:year>/ay-<str:month>-gönderileri/', views.MountArticleListView.as_view(), name='mount_list'),
]

base/models/home.py
from autoslug import AutoSlugField
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field


class Home(models.Model):
    name = models.CharField(max_length=100, default="Anasayfa", unique=True, verbose_name='Site Adı')
    email = models.EmailField(verbose_name='Email', blank=True, help_text='Email göndermek için kullanılacak')
    email_password = models.CharField(verbose_name='Email şifresi', max_length=100, blank=True)

    created = models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')
    updated = models.DateTimeField(auto_now=True, verbose_name='Düzenlendi')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created']
        verbose_name = 'Ayar'
        verbose_name_plural = 'Ayarlar'


class MetaTags(models.Model):
    meta_type = [
        ('genel', 'genel'),
        ('facebook', 'facebook'),
        ('twitter', 'twitter'),
        ('google', 'google'),
        ('canonical', 'canonical'),
    ]
    page = models.ForeignKey(Home, on_delete=models.CASCADE, related_name='meta_tags')
    tag = models.CharField(verbose_name='Tag türü', max_length=100, choices=meta_type)
    name = models.CharField(max_length=50, verbose_name='Tag Adı')
    content = models.TextField(verbose_name='Tag İçeriği')

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name = 'Meta Tag'
        verbose_name_plural = 'Meta Taglar'


class Hero(models.Model):
    page = models.ForeignKey(Home, on_delete=models.CASCADE, related_name='heros')

    image = models.ImageField(upload_to='Hero/', verbose_name="Foto")
    title = models.CharField(max_length=100, verbose_name="Başlık")
    content = CKEditor5Field(config_name="extends", verbose_name="İçerik")
    slug = AutoSlugField(populate_from='title')
    video = models.URLField(verbose_name='Video URL', blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']
        verbose_name = 'Başlık'
        verbose_name_plural = 'Başlık'


class Clients(models.Model):
    page = models.ForeignKey(Home, on_delete=models.CASCADE, related_name='clients')
    name = models.CharField(max_length=100, verbose_name="Ad")
    logo = models.ImageField(verbose_name="Logo", upload_to="Clients/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Müşteri - Sponsor'
        verbose_name_plural = 'Müşteri - Sponsor'


class AboutCategory(models.Model):
    title = models.CharField(max_length=100, verbose_name="Tab Panel")
    icon = models.CharField(
        max_length=50, verbose_name="Icon ADI",
        help_text="Ör : binoculars <h6>İngilizce yazın. Daha fazlası için <a href='https://icons.getbootstrap.com/' target='_blank'>Tıklayın</a></h6>"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Hakkımızda Kategori'
        verbose_name_plural = 'Hakkımızda Kategori'


class AboutTab(models.Model):
    page = models.ForeignKey(Home, on_delete=models.CASCADE, related_name='about')
    category = models.ForeignKey(AboutCategory, on_delete=models.CASCADE)

    content = CKEditor5Field(config_name="extends", verbose_name='İçerik')
    image = models.ImageField(verbose_name="Hakkımızda Görüntüsü", upload_to="About/")

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.category.title

    class Meta:
        verbose_name = 'Hakkımızda'
        verbose_name_plural = "Hakkımızda"


class Services(models.Model):
    class IconType(models.TextChoices):
        FONTAWESOME = 'fa', 'Fontawesome'
        BOOTSTRAP = 'bi', 'Bootstrap'

    page = models.ForeignKey(Home, on_delete=models.CASCADE, related_name='services')

    title = models.CharField(max_length=100, verbose_name="Hizmet Adı")

    icon_type = models.CharField(verbose_name='İcon Türü', max_length=2, choices=IconType.choices,
                                 default=IconType.BOOTSTRAP,  help_text="<h6>Daha fazlası için, <a href='https://icons.getbootstrap.com/' target='_blank'>Bootstrap iconları</a>, <a href='https://fontawesome.com/search' target='_blank'>Fontawesome iconları</a></h6>")

    icon = models.CharField(
        max_length=50, verbose_name="Icon Sınıfı",
        help_text="Ör : bi bi-binoculars"
    )

    image = models.ImageField(upload_to='Services/', verbose_name="Foto")
    content = CKEditor5Field(config_name="extends", help_text="Hizmetinizi detaylı açıklayın",
                             verbose_name='Hizmet İçeriği')
    slug = AutoSlugField(populate_from='title')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Hizmetlerimiz'
        verbose_name_plural = 'Hizmetlerimiz'


class FrequentlyAskedQuestions(models.Model):
    page = models.ForeignKey(Home, on_delete=models.CASCADE, related_name='frequently')

    question = models.CharField(max_length=100, verbose_name='Soru')
    answer = models.TextField(verbose_name="Cevap")

    created = models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')
    updated = models.DateTimeField(auto_now=True, verbose_name='Güncellenme')

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'Sıkça Sorulan Sorular'
        verbose_name_plural = 'Sıkça Sorulan Sorular'
        ordering = ['-created']


class Team(models.Model):
    page = models.ForeignKey(Home, on_delete=models.CASCADE, related_name='teams')

    image = models.ImageField(verbose_name="Foto", upload_to="Teams/")
    name = models.CharField(verbose_name="Ad Soyad", max_length=100)
    department = models.CharField(verbose_name="Bölüm", max_length=100)

    twitter = models.CharField(verbose_name="Twitter", max_length=100, blank=True)
    instagram = models.CharField(verbose_name="Instagram", max_length=100, blank=True)
    facebook = models.CharField(verbose_name="Facebook", max_length=100, blank=True)
    linkedin = models.CharField(verbose_name="Linkedin", max_length=100, blank=True)
    github = models.CharField(verbose_name="Github", max_length=100, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created']
        verbose_name = 'Ekip Arkadaşlarımız'
        verbose_name_plural = 'Ekip Arkadaşlarımız'


class Contact(models.Model):
    page = models.ForeignKey(Home, on_delete=models.CASCADE, related_name='contacts')

    email = models.EmailField(verbose_name="Email", max_length=100)
    address = models.CharField(verbose_name="Adres", max_length=100)
    phone = models.CharField(verbose_name="Telefon", max_length=100)

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'İletişim Bilgileri'

    class Meta:
        ordering = ['-created']
        verbose_name = 'İletişim Bilgileri'
        verbose_name_plural = 'İletişim Bilgileri'


class Subscriber(models.Model):
    email = models.EmailField(verbose_name="Email", max_length=100, unique=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Abone"
        verbose_name_plural = "Aboneler"


class SocialNetwork(models.Model):
    page = models.ForeignKey(Home, on_delete=models.CASCADE, related_name='social_networks')
    name = models.CharField(verbose_name="Social Medya", max_length=100,
                            help_text="facebook, twitter, instagram, linkedin, github")
    url = models.URLField(verbose_name="Social Medya URL")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Social Medya"
        verbose_name_plural = "Social Medya"

templates/pages/blog-details.html
{% extends 'layout/base.html' %}
{% load thumbnail hitcount_tags %}

{% block meta_tags %}
    <link rel="shortcut icon" href="{{ object.cover.url }}" type="image/x-icon">
    <meta name="description" content="{{ object.title }}">
    <meta name="keywords" content="{{ object.slug }}, {{ object.title }}, {{ object.category }}">
    <meta name="author" content="{{ object.author }}">
    <meta property="og:title" content="{{ object.title }}">
    <meta property="og:description" content="{{ object.title }}">
    <meta property="og:image" content="{{ object.cover.url }}">
    <meta property="og:image:width" content="1024">
    <meta property="og:image:height" content="1024">
    <meta property="og:url" content="{% url 'post:blog_details' object.category.title|slugify object.slug %}">
    <meta property="og:type" content="article">
    <link rel="canonical" href="{{ object.cover.url }}">
{% endblock %}

{% block title %}Makale | {{ object.title }}{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">

            <div class="col-lg-8">
                {% include 'includes/message.html' %}
                <!-- Blog Details Section -->
                <section id="blog-details" class="blog-details section">
                    <div class="container">

                        <article class="article">
                            {% if request.user == object.author %}
                                <li class="d-flex align-items-center float-end" title="Düzenle">
                                    <a href="{% url 'admin:index' %}post/articlemodel/{{ object.pk }}/change/">
                                        <i class="bi bi-pen text-primary"></i>
                                    </a>
                                </li>
                            {% endif %}
                            <a href="{{ object.cover.url }}" title="{{ object.title }}"
                               data-gallery="identifier" class="text-decoration-none">
                                {% thumbnail object.cover "1920x1080" padding=True quality=100 crop="center" as im %}
                                    <img src="{{ im.url }}" class="glightbox card-img-top rounded"
                                         alt="{{ object.title }}">
                                {% endthumbnail %}
                            </a>
                            <h2 class="title">{{ object.title }}</h2>

                            <div class="meta-top">
                                <ul>

                                    <li class="d-flex align-items-center">
                                        <i class="bi bi-folder"></i>
                                        <a href="{% url 'post:category_list' object.category.title %}">{{ object.category.title.title }}</a>
                                    </li>

                                    <li class="d-flex align-items-center">
                                        <i class="bi bi-clock"></i>
                                        <a href="{% url 'post:mount_list' object.created_at.year object.created_at.month %}">
                                            <time datetime="{{ object.created_at.date }}">{{ object.created_at.date }}</time>
                                        </a>
                                    </li>

                                    <li class="d-flex align-items-center">
                                        <i class="bi bi-chat-dots"></i>
                                        <a href="#comments">{{ object.comments.count }} Yorum</a>
                                    </li>

                                </ul>

                            </div><!-- End meta top -->

                            <div class="content" id="printableArea">
                                {{ object.content|safe }}
                            </div><!-- End post content -->

                            <div class="meta-bottom">

                                <ul class="cats">

                                    <li title="Okunma Sayısı">
                                        <i class="bi bi-eye">{% get_hit_count for object %}</i>
                                    </li>


                                    <li class="btn btn-sm list-unstyled" onclick="printDiv('printableArea')">
                                        <i class="bi bi-printer">Yazdır</i>
                                    </li>


                                    <li class="social-links float-end">
                                        <a title="Paylaş"
                                           href="https://twitter.com/intent/tweet?text={{ request.build_absolute_uri }}"><i
                                                class="bi bi-twitter-x"></i></a>
                                        <a title="Paylaş"
                                           href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}"><i
                                                class="bi bi-facebook"></i></a>
                                        <a title="Paylaş"
                                           href="https://api.whatsapp.com/send?text={{ request.build_absolute_uri }}"><i
                                                class="bi bi-whatsapp"></i></a>
                                    </li>

                                </ul>

                            </div><!-- End meta bottom -->

                        </article>
                    </div>

                </section><!-- /Blog Details Section -->

                <!-- Blog Author Section -->
                <section id="blog-author" class="blog-author section">

                    <div class="container">
                        <div class="author-container d-flex align-items-center">

                            <div>
                                <h4 class="border-bottom fst-italic mb-2">Yazar Hakkında</h4>
                                <a href="{% url 'post:author_list' object.author %}">
                                    <h5>{{ object.author.username }}</h5></a>
                                <p>
                                    Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus
                                    accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse
                                    et accusantium ut unde voluptas.
                                </p>
                            </div>
                        </div>
                    </div>

                </section><!-- /Blog Author Section -->

                <!-- Blog Comments Section -->
                <section id="comments" class="blog-comments section">

                    <div class="container">

                        {% if object.comments.count == 0 %}
                            <h6 class="comments-count">Gönderiye henüz yorum yapılmamıştır.</h6>
                        {% else %}
                            <h4 class="comments-count">{{ object.comments.count }} Yorum</h4>
                        {% endif %}

                        {% for comment in object.comments.all %}
                            <div id="comment-{{ forloop.counter }}" class="comment">
                                <div class="d-flex">
                                    <div class="comment-img img-thumbnail"></div>
                                    <div>
                                        <h5><a href="">{{ comment.author }}</a></h5>
                                        <time datetime="{{ comment.created_at }}">{{ comment.created_at }}</time>
                                        <p>
                                            {{ comment.comment }}
                                        </p>
                                        <div class="text-danger justify-content-end fst-italic"><a
                                                href="{% url 'post:comment_report' comment.pk %}">Yorumu rapor et</a>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- End comment #1 -->
                        {% endfor %}

                    </div>

                </section><!-- /Blog Comments Section -->

                <!-- Comment Form Section -->
                <section id="comment-form" class="comment-form section">
                    <div class="container">

                        <form method="get">

                            <h4>Yorum</h4>
                            <p>Email adresiniz paylaşılmayacak</p>

                            <div class="row">
                                <div class="col form-group">
                                    <textarea name="comment" class="form-control" placeholder="Yorumunuz*"
                                              required></textarea>
                                </div>
                            </div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Yorum Yap</button>
                            </div>

                        </form>

                    </div>
                </section><!-- /Comment Form Section -->

            </div>

            <div class="col-lg-4 sidebar">

                <div class="widgets-container">

                    <!-- Search Widget -->
                    <div class="search-widget widget-item d-none d-lg-block">

                        <h3 class="widget-title">Makale Ara</h3>
                        <form action="{% url 'post:blog' %}" method="get">
                            <input type="text" placeholder="Kategori veya Başlık" name="ara" id="ara" autocomplete="off"
                                   value="{{ request.GET.ara }}">
                            <button type="submit" title="Search"><i class="bi bi-search"></i></button>
                        </form>

                    </div><!--/Search Widget -->

                    <!-- Categories Widget -->
                    <div class="categories-widget widget-item">

                        <h3 class="widget-title">Kategoriler</h3>
                        <ul class="mt-3">

                            {% for category in recent_post %}
                                {% ifchanged %}
                                    <li>
                                        <a href="{% url 'post:category_list' category.category.title %}">{{ category.category.title.title }}</a>
                                    </li>
                                {% endifchanged %}
                            {% endfor %}
                        </ul>

                    </div><!--/Categories Widget -->

                    <!-- Recent Posts Widget -->
                    <div class="recent-posts-widget widget-item">

                        <h3 class="widget-title border-bottom">Son Gönderiler</h3>

                        {% for post in recent_post %}
                            <div class="post-item">
                                <img src="{{ post.cover.url }}" alt="" class="flex-shrink-0">
                                <div>
                                    <h4><a href="{% url 'post:blog_details' post.pk post.slug %}">{{ post.title }}</a>
                                    </h4>
                                    <time datetime="{{ post.created_at.date }}">{{ post.created_at.date }}</time>
                                </div>
                            </div><!-- End recent post item-->
                        {% endfor %}

                    </div><!--/Recent Posts Widget -->

                    <!-- Tags Widget -->
                    <div class="tags-widget widget-item">

                        <h3 class="widget-title">Etiketler</h3>
                        <ul>
                            {% for tag in object.article_tags.all %}
                                <li><a href="{% url 'post:tags_list' tag.tags %}">{{ tag.tags.title }}</a></li>
                            {% endfor %}

                        </ul>

                    </div><!--/Tags Widget -->

                </div>

            </div>

        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        function printDiv(divName) {
            var printContents = document.getElementById(divName).innerHTML;
            var originalContents = document.body.innerHTML;

            document.body.innerHTML = printContents;

            window.print();

            document.body.innerHTML = originalContents;
        }
    </script>
{% endblock %}

templates/pages/blog.html
{% extends 'layout/base.html' %}

{% block title %}Blog{% endblock %}

{% block content %}

    {% include 'includes/breadcrumbs.html' %}

    <main class="main">

        <div class="container">

            <div class="row">

                {% include 'includes/search.html' %}

                {% include 'includes/message.html' %}

                <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                    <!-- Blog Posts Section -->
                    <section id="blog-posts" class="blog-posts section">

                        <div class="container">

                            <div class="row gy-4">
                                {% if object_list %}
                                    {% for object in object_list %}
                                        <div class="col-xxl-4 col-xl-4 col-sm-12 col-md-12 col-lg-6">
                                            <article>

                                                <div class="post-img">
                                                    <img src="{{ object.cover.url }}" alt=""
                                                         class="img-fluid rounded">
                                                </div>

                                                <h2 class="title">
                                                    <a href="{% url 'post:blog_details' object.pk object.slug %}">{{ object.title }}</a>
                                                </h2>

                                                <div class="meta-top">

                                                    <ul>

                                                        <li class="d-flex align-items-center">
                                                            <i class="bi bi-folder"></i>
                                                            <a href="{% url 'post:category_list' object.category.title %}"
                                                               title="Kategori">{{ object.category.title.title }}</a>
                                                        </li>

                                                        <li class="d-flex align-items-center">
                                                            <i class="bi bi-clock"></i>
                                                            <a href="{% url 'post:mount_list' object.created_at.year object.created_at.month %}">
                                                                <time>{{ object.created_at.date }}</time>
                                                            </a>
                                                        </li>

                                                        <li class="d-flex align-items-center">
                                                            <i class="bi bi-chat-dots"></i>
                                                            <a href="{% url 'post:blog_details' object.pk object.slug %}#comments">{{ object.comments.count }}
                                                                Yorum</a>
                                                        </li>

                                                    </ul>

                                                </div>

                                                <div class="content">
                                                    <p>
                                                        {{ object.content|safe|truncatewords_html:20 }}
                                                    </p>

                                                    <div class="read-more">
                                                        <a href="{% url 'post:blog_details' object.pk object.slug %}">Ayrıntılar
                                                            &raquo;</a>
                                                    </div>
                                                </div>

                                            </article>
                                        </div><!-- End post list item -->
                                    {% endfor %}
                                {% else %}

                                {% endif %}

                            </div><!-- End blog posts list -->

                        </div>

                    </section>
                    <!-- /Blog Posts Section -->

                    {% include 'includes/paginator.html' %}
                </div>

            </div>

        </div>

    </main>



{% endblock %}

templates/pages/index.html
{% extends 'layout/base.html' %}

{% block title %} Anasayfa {% endblock %}

{% block content %}
    
    {% include 'includes/message.html' %}

    {% include 'includes/hero.html' %}

    {% include 'includes/clients.html' %}

    {% include 'includes/about.html' %}

    {% include 'includes/services.html' %}

    {% include 'includes/faq.html' %}

    {% include 'includes/team.html' %}

{% endblock %}

templates/pages/pricing.html
{% extends 'layout/base.html' %}

{% block title %}Fiyatlar{% endblock %}

{% block content %}

    {% include 'includes/breadcrumbs.html' %}

    {% include 'includes/pricing.html' %}

{% endblock %}

templates/pages/service-details.html
{% extends 'layout/base.html' %}


{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}

    {% include 'includes/breadcrumbs.html' %}

    <!-- Service Details Section -->
    <section id="service-details" class="service-details section">

        <div class="container">

            <div class="row gy-5">

                <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">

                    <div class="service-box">
                        <h4>Hizmetlerimiz</h4>
                        <div class="services-list">
                            {% for services in services_list %}
                                <a href="{% url 'base:service_detail' services.slug %}" {% if services.slug in request.get_full_path %}class="active"{% endif %}>
                                    <i class="bi bi-arrow-right-circle"></i><span>{{ services.title }}</span>
                                </a>
                            {% endfor %}
                        </div>
                    </div><!-- End Services List -->

                    <div class="service-box">
                        <h4>Download Catalog</h4>
                        <div class="download-catalog">
                            <a href="#"><i class="bi bi-filetype-pdf"></i><span>Catalog PDF</span></a>
                            <a href="#"><i class="bi bi-file-earmark-word"></i><span>Catalog DOC</span></a>
                        </div>
                    </div><!-- End Services List -->

                    <div class="help-box d-flex flex-column justify-content-center align-items-center">
                        <i class="bi bi-headset help-icon"></i>
                        <h4>Have a Question?</h4>
                        <p class="d-flex align-items-center mt-2 mb-0"><i class="bi bi-telephone me-2"></i> <span>+1 5589 55488 55</span>
                        </p>
                        <p class="d-flex align-items-center mt-1 mb-0"><i class="bi bi-envelope me-2"></i> <a
                                href="mailto:contact@example.com">contact@example.com</a></p>
                    </div>

                </div>

                <div class="col-lg-8 ps-lg-5" data-aos="fade-up" data-aos-delay="200">
                    <img src="{{ object.image.url }}" alt="" class="glightbox img-fluid services-img rounded">
                    {{ object.content|safe }}
                </div>

            </div>

        </div>

    </section><!-- /Service Details Section -->
{% endblock %}