base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('starter/', views.StarterView.as_view(), name='starter'),
    path('hizmetlerimiz/<slug>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path('iletisim/', views.ContactView, name='contact'),
    path('subscriber/', views.SubscriberView, name='subscriber'),
    path('fiyatlandirma/', views.PricingView.as_view(), name='pricing'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_ckeditor_5.views import upload_file
from base.models import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path("ckeditor5/image_upload/", upload_file, name="ckeditor_upload_file"),
    path(r"images-handler/", include("galleryfield.urls")),
    path('', include('base.urls')),
    path('', include('post.urls')),
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


try:
    site = Home.objects.latest('created')
    admin.site.site_title = site.name
    admin.site.site_header = site.name
    admin.site.index_title = site.name
    admin.site.name = site.name
except:
    pass

templates/includes/blue_carosel.html
<!-- The Gallery as inline carousel, can be positioned anywhere on the page -->
<div
        id="blueimp-gallery-carousel"
        class="blueimp-gallery blueimp-gallery-carousel rounded"
        aria-label="image carousel"
>
    <div class="slides" aria-live="off"></div>
    <h3 class="title"></h3>
    <a
            class="prev"
            aria-controls="blueimp-gallery-carousel"
            aria-label="previous slide"
    ></a>
    <a
            class="next"
            aria-controls="blueimp-gallery-carousel"
            aria-label="next slide"
    ></a>
    <a
            class="play-pause"
            aria-controls="blueimp-gallery-carousel"
            aria-label="play slideshow"
            aria-pressed="true"
            role="button"
    ></a>
    <ol class="indicator"></ol>
</div>
<!-- The Gallery as lightbox dialog, should be a document body child element -->
<div
        id="blueimp-gallery"
        class="blueimp-gallery"
        aria-label="image gallery"
        aria-modal="true"
        role="dialog"
>
    <div class="slides" aria-live="polite"></div>
    <h3 class="title"></h3>
    <a
            class="prev"
            aria-controls="blueimp-gallery"
            aria-label="previous slide"
            aria-keyshortcuts="ArrowLeft"
    ></a>
    <a
            class="next"
            aria-controls="blueimp-gallery"
            aria-label="next slide"
            aria-keyshortcuts="ArrowRight"
    ></a>
    <a
            class="close"
            aria-controls="blueimp-gallery"
            aria-label="close"
            aria-keyshortcuts="Escape"
    ></a>
    <a
            class="play-pause"
            aria-controls="blueimp-gallery"
            aria-label="play slideshow"
            aria-keyshortcuts="Space"
            aria-pressed="false"
            role="button"
    ></a>
    <ol class="indicator"></ol>
</div>

<div id="links" class=" blueimp-gallery-single img-rounded">
    <img src="{{ object.cover.url }}" alt="{{ object.cover.name }}"  />
</div>

templates/includes/clients.html
{% load home %}
{% clients as object_list %}


{% if object_list %}

    <!-- Clients Section -->
    <section id="clients" class="clients section">

        <!-- Section Title -->
        <div class="container section-title" data-aos="fade-up">
            <h2>Destekçilerimiz</h2>
        </div><!-- End Section Title -->

        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="swiper init-swiper">
                <script type="application/json" class="swiper-config">
                    {
                      "loop": true,
                      "speed": 600,
                      "autoplay": {
                        "delay": 5000
                      },
                      "slidesPerView": "auto",
                      "pagination": {
                        "el": ".swiper-pagination",
                        "type": "bullets",
                        "clickable": true
                      },
                      "breakpoints": {
                        "320": {
                          "slidesPerView": 2,
                          "spaceBetween": 40
                        },
                        "480": {
                          "slidesPerView": 3,
                          "spaceBetween": 60
                        },
                        "640": {
                          "slidesPerView": 4,
                          "spaceBetween": 80
                        },
                        "992": {
                          "slidesPerView": 6,
                          "spaceBetween": 120
                        }
                      }
                    }
                </script>
                <div class="swiper-wrapper align-items-center">
                    {% for client in object_list %}
                        <div class="swiper-slide">
                            <img src="{{ client.logo.url }}" class="img-fluid" alt="{{ client.name }}">
                        </div>
                    {% endfor %}
                </div>
                <div class="swiper-pagination"></div>
            </div>

        </div>

    </section><!-- /Clients Section -->

{% else %}

    <!-- Clients Section -->
    <section id="clients" class="clients section">

        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="swiper init-swiper">
                <script type="application/json" class="swiper-config">
                    {
                      "loop": true,
                      "speed": 600,
                      "autoplay": {
                        "delay": 5000
                      },
                      "slidesPerView": "auto",
                      "pagination": {
                        "el": ".swiper-pagination",
                        "type": "bullets",
                        "clickable": true
                      },
                      "breakpoints": {
                        "320": {
                          "slidesPerView": 2,
                          "spaceBetween": 40
                        },
                        "480": {
                          "slidesPerView": 3,
                          "spaceBetween": 60
                        },
                        "640": {
                          "slidesPerView": 4,
                          "spaceBetween": 80
                        },
                        "992": {
                          "slidesPerView": 6,
                          "spaceBetween": 120
                        }
                      }
                    }
                </script>
                <div class="swiper-wrapper align-items-center">
                    <div class="swiper-slide"><img src="/static/assets/img/clients/iyzico_wtihebg_blue.png" class="img-fluid"
                                                   alt=""></div>
                    <div class="swiper-slide"><img src="/static/assets/img/clients/visa-brandmark-blue-1960x622.png" class="img-fluid"
                                                   alt=""></div>
                    <div class="swiper-slide"><img src="/static/assets/img/clients/ma_symbol_opt_73_3x.png" class="img-fluid"
                                                   alt=""></div>
                    <div class="swiper-slide"><img src="/static/assets/img/clients/3d_protection.png" class="img-fluid"
                                                   alt=""></div>
                    <div class="swiper-slide"><img src="/static/assets/img/clients/client-6.png" class="img-fluid"
                                                   alt=""></div>
                    <div class="swiper-slide"><img src="/static/assets/img/clients/client-8.png" class="img-fluid"
                                                   alt=""></div>
                </div>
                <div class="swiper-pagination"></div>
            </div>

        </div>

    </section><!-- /Clients Section -->

{% endif %}

templates/includes/favicon.html
<!-- Favicons -->
<link href="/static/assets/img/favicon.png" rel="icon">
<link href="/static/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

templates/includes/footer.html
{% load home %}
{% base_settings as object %}
{% contact as contact %}

<footer id="footer" class="footer dark-background">

    <div class="container footer-top">
        <div class="row gy-4">
            <div class="col-lg-4 col-md-6 footer-about">
                <a href="/" class="logo d-flex align-items-center">
                    <span class="sitename">{{ object.name.title }}</span>
                </a>
                <div class="footer-contact pt-3">
                    <p>{{ contact.address }}</p>
                    <p class="mt-3"><strong>Telefon:</strong> <span>{{ contact.phone }}</span></p>
                    <p><strong>Email:</strong> <span>{{ contact.email }}</span></p>
                </div>
                <div class="social-links d-flex mt-4">
                    {% if object.social_networks %}
                        {% for social in object.social_networks.all %}
                            <a href="{{ social.url }}"><i class="bi bi-{{ social.name }}"></i></a>
                        {% endfor %}
                    {% else %}
                        <a href=""><i class="bi bi-twitter-x"></i></a>
                        <a href=""><i class="bi bi-facebook"></i></a>
                        <a href=""><i class="bi bi-instagram"></i></a>
                        <a href=""><i class="bi bi-linkedin"></i></a>
                    {% endif %}
                </div>
            </div>

            <div class="col-lg-2 col-md-3 footer-links">
                <h4>Faydalı Linkler</h4>
                <ul>
                    <li><a href="/">Anasayfa</a></li>
                    <li><a href="/#about">Hakkımızda</a></li>
                    <li><a href="/#services">Hizmetlerimiz</a></li>
                    <li><a href="#">Kullanım Koşul ve Şartları</a></li>
                    <li><a href="#">Gizlilik Politikası</a></li>
                </ul>
            </div>

            <div class="col-lg-2 col-md-3 footer-links">
                <h4>Hizmetlerimiz</h4>
                <ul>
                    {% if object.services %}
                        {% for service in object.services.all %}
                            <li><a href="{% url 'base:service_detail' service.slug %}">{{ service.title }}</a></li>
                        {% endfor %}
                    {% else %}
                        <li><a href="#">Web Design</a></li>
                        <li><a href="#">Web Development</a></li>
                        <li><a href="#">Product Management</a></li>
                        <li><a href="#">Marketing</a></li>
                        <li><a href="#">Graphic Design</a></li>
                    {% endif %}
                </ul>
            </div>

            <div class="col-lg-4 col-md-12 footer-newsletter">
                <h4>Abonelik</h4>
                <p>Bültenimize abone olun ve ürünlerimiz ve hizmetlerimizle ilgili en son haberleri alın!</p>
                <form action="{% url 'base:subscriber' %}" method="post" class="php-email-form" id='subscribeForm'>
                    {% csrf_token %}
                    <div class="newsletter-form">
                        <input type="email" name="email" id="email" placeholder="Email" autocomplete="on"
                               value="{{ request.POST.email }}">
                        <input type="submit" value="Abone ol">
                    </div>
                </form>
            </div>

            <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            <p>One fine body&hellip;</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
        </div>
    </div>

    <div class="container copyright text-center mt-4">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">{{ object.name.title }}</strong> <span>Tüm hakları saklıdır.</span>
        </p>

    </div>

</footer>

templates/includes/hero.html
{% load home %}
{% hero_list as object_list %}

{% if object_list %}
    {% for obj in object_list %}
        <!-- Hero Section -->
        <section id="hero" class="hero section rounded">

            <img src="{{ obj.image.url }}" alt="{{ obj.title }}" data-aos="fade-in">

            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <h2 data-aos="fade-up" data-aos-delay="100">{{ obj.title }}</h2>
                        <p data-aos="fade-up" data-aos-delay="200">
                            {{ obj.content|safe }}
                        </p>
                        <div class="d-flex mt-4" data-aos="fade-up" data-aos-delay="300">
                            <a href="/#about" class="btn-get-started">Hakkımızda</a>
                            <a href="{{ obj.video }}" class="glightbox btn-watch-video d-flex align-items-center" data-aos="fade-up" data-aos-delay="400">
                                <i class="bi bi-play-circle"></i>
                                <span>Videoyu İzle</span>
                            </a>
                        </div>

                    </div>
                </div>
            </div>

        </section><!-- /Hero Section -->
    {% endfor %}
{% else %}
    <!-- Hero Section -->
    <section id="hero" class="hero section rounded">

        <img src="/static/assets/img/hero-bg.jpg" alt="" data-aos="fade-in">

        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2 data-aos="fade-up" data-aos-delay="100">Bettter digital experience with Presento</h2>
                    <p data-aos="fade-up" data-aos-delay="200">We are team of talented designers making websites with
                        Bootstrap</p>
                    <div class="d-flex mt-4" data-aos="fade-up" data-aos-delay="300">
                        <a href="#about" class="btn-get-started">Get Started</a>
                        <a href="https://www.youtube.com/watch?v=Y7f98aduVJ8"
                           class="glightbox btn-watch-video d-flex align-items-center"><i
                                class="bi bi-play-circle"></i><span>Watch Video</span></a>
                    </div>

                </div>
            </div>
        </div>

    </section><!-- /Hero Section -->
{% endif %}

templates/includes/js.html
{% load static %}
<!-- Vendor JS Files -->
<script src="/static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/static/assets/vendor/aos/aos.js"></script>
<script src="/static/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="/static/assets/vendor/swiper/swiper-bundle.min.js"></script>
<script src="/static/assets/vendor/purecounter/purecounter_vanilla.js"></script>
<script src="/static/assets/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
<script src="/static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
<script src="{% static 'vendor/jquery.blueimp-gallery.min.js' %}?{% now 'U' %}"></script>

<script src="{% static 'js/galleryfield-ui.js' %}?{% now 'U' %}"></script>


<!-- Main JS File -->
<script src="/static/assets/js/main.js?{% now 'U' %}"></script>
<script href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


<script>
    blueimp.Gallery(document.getElementById('links').getElementsByTagName('a'), {
        container: '#blueimp-gallery-carousel',
        carousel: true

    })
</script>

<script>
    var data = {
        title: 'JavaScript Templates',
        license: {
            name: 'MIT license',
            url: 'https://opensource.org/licenses/MIT'
        },
        features: ['lightweight & fast', 'powerful', 'zero dependencies']
    }
</script>

<script>
    var fullscreenOptions = {
        // Defines if the gallery should open in fullscreen mode:
        fullscreen: true
    }
</script>

<script>
    var indicatorOptions = {
        // The tag name, Id, element or querySelector of the indicator container:
        indicatorContainer: 'ol',
        // The class for the active indicator:
        activeIndicatorClass: 'active',
        // The list object property (or data attribute) with the thumbnail URL,
        // used as alternative to a thumbnail child element:
        thumbnailProperty: 'thumbnail',
        // Defines if the gallery indicators should display a thumbnail:
        thumbnailIndicators: true

    }
</script>

templates/includes/message.html
{% if messages %}
    {% for message in messages %}

        <div class="alert alert-{{ message.tags }} alert-dismissible shadow-soft fade show mt-1" role="alert">

            <span class="alert-inner--icon">
                {% if message.tags == 'error' %}
                    <span class="bi bi-hand-thumbs-down"></span>
                {% elif message.tags == 'success' %}
                    <span class="bi bi-hand-thumbs-up"></span>
                {% elif message.tags == 'info' %}
                    <span class="bi bi-info-circle"></span>
                {% elif message.tags == 'warning' %}
                    <span class="bi bi-info-circle"></span>
                {% endif %}
            </span>

            <span class="alert-inner--text"><strong>{{ message }}</strong></span>

            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

        </div>

    {% endfor %}
{% endif %}

templates/includes/meta.html
{% load home %}
{% meta_tags as meta_list %}

{% if meta_list %}
    {% for meta in meta_list %}
        <!-- {{ meta.tag }} tags -->
        <meta name="{{ meta.name }}" content="{{ meta.content }}">
    {% endfor %}
{% else %}
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <link rel="canonical" href="https://orneksite.com/ana-icerik"/>


    <meta property="og:url" content="{{ pageUrl }}">
    <meta property="og:image" content="{{ imageUrl }}">
    <meta property="og:description" content="{{ description }}">
    <meta property="og:title" content="{{ pageTitle }}">
    <meta property="og:site_name" content="{{ siteTitle }}">
    <meta property="og:see_also" content="{{ homepageUrl }}">

    <meta itemprop="name" content="{{ pageTitle }}">
    <meta itemprop="description" content="{{ description }}">
    <meta itemprop="image" content="{{ imageUrl }}">

    <meta name="twitter:card" content="summary">
    <meta name="twitter:url" content="{{ pageUrl }}">
    <meta name="twitter:title" content="{{ pageTitle }}">
    <meta name="twitter:description" content="{{ description }}">
    <meta name="twitter:image" content="{{ imageUrl }}">
{% endif %}

templates/includes/paginator.html
<!-- Blog Pagination Section -->
<section id="blog-pagination" class="blog-pagination section">

    <div class="container">
        <div class="d-flex justify-content-center">
            <ul>
                {% if page_obj.has_previous %}
                    <li>
                        <a class="page-link" aria-label="ilk sayfa" title="ilk sayfa"
                           href="?page=1">
                            <span class="bi bi-chevron-double-left"></span>
                        </a>
                    </li>
                    <li>
                        <a class="page-link rounded" aria-label="önceki sayfa"
                           title="önceki sayfa"
                           href="?page={{ page_obj.previous_page_number }}">
                            <span class="bi bi-chevron-left"></span>
                        </a>
                    </li>
                {% endif %}
                {% for number in page_obj.paginator.page_range %}
                    {% if page_obj.number == number %}
                        <li class="page-item active">
                            <a class="page-link active" href="#">{{ number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ number }}">{{ number }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link rounded" aria-label="first link"
                           title="sonraki sayfa"
                           href="?page={{ page_obj.next_page_number }}">
                            <span class="bi bi-chevron-right"></span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" aria-label="first link" title="son sayfa"
                           href="?page={{ page_obj.paginator.num_pages }}">
                            <span class="bi bi-chevron-double-right"></span>
                        </a>
                    </li>

                {% else %}

                    <li class="page-item">
                        <a class="page-link" aria-label="first link"
                           href="#">
                            <span class="bi bi-chevron-double-right"></span>
                        </a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>

</section><!-- /Blog Pagination Section -->

templates/includes/services.html
{% load home %}
{% services_list as obj_list %}

{% if obj_list %}

    <!-- Services Section -->
    <section id="services" class="services section section-bg dark-background">

        <!-- Section Title -->
        <div class="container section-title" >
            <h2>Hizmetlerimiz</h2>
            <p>Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
        </div><!-- End Section Title -->

        <div class="container">
            <div class="row gy-4">
                {% for service in obj_list %}
                    <div class="col-md-6" >
                        <div class="service-item d-flex position-relative h-100">
                            {% if service.icon_type == 'fa' %}
                                <i class="{{ service.icon.lower }} icon flex-shrink-0 mt-4"></i>
                            {% elif service.icon_type == 'bi' %}
                                <i class="{{ service.icon.lower }} icon flex-shrink-0"></i>
                            {% endif %}

                            <div>
                                <h4 class="title">
                                    <a href="{% url 'base:service_detail' service.slug %}" class="stretched-link">
                                        {{ service.title }}
                                    </a>
                                </h4>
                                <p class="description">
                                    {{ service.content|safe|truncatewords_html:10 }}</p>
                            </div>
                        </div>
                    </div><!-- End Service Item -->
                {% endfor %}
            </div>
        </div>

    </section><!-- /Services Section -->

{% else %}
    <!-- Services Section -->
    <section id="services" class="services section section-bg dark-background">

        <!-- Section Title -->
        <div class="container section-title" >
            <h2>Services</h2>
            <p>Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
        </div><!-- End Section Title -->

        <div class="container">

            <div class="row gy-4">

                <div class="col-md-6" >
                    <div class="service-item d-flex position-relative h-100">
                        <i class="bi bi-briefcase icon flex-shrink-0"></i>
                        <div>
                            <h4 class="title"><a href="service-details.html" class="stretched-link">Lorem Ipsum</a></h4>
                            <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias
                                excepturi sint occaecati cupiditate non provident</p>
                        </div>
                    </div>
                </div><!-- End Service Item -->

                <div class="col-md-6" >
                    <div class="service-item d-flex position-relative h-100">
                        <i class="bi bi-card-checklist icon flex-shrink-0"></i>
                        <div>
                            <h4 class="title"><a href="service-details.html" class="stretched-link">Dolor Sitema</a>
                            </h4>
                            <p class="description">Minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                                aliquip ex ea commodo consequat tarad limino ata</p>
                        </div>
                    </div>
                </div><!-- End Service Item -->

                <div class="col-md-6" >
                    <div class="service-item d-flex position-relative h-100">
                        <i class="bi bi-bar-chart icon flex-shrink-0"></i>
                        <div>
                            <h4 class="title"><a href="service-details.html" class="stretched-link">Sed ut
                                perspiciatis</a></h4>
                            <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
                                dolore eu fugiat nulla pariatur</p>
                        </div>
                    </div>
                </div><!-- End Service Item -->

                <div class="col-md-6" >
                    <div class="service-item d-flex position-relative h-100">
                        <i class="bi bi-binoculars icon flex-shrink-0"></i>
                        <div>
                            <h4 class="title"><a href="service-details.html" class="stretched-link">Magni Dolores</a>
                            </h4>
                            <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
                                officia deserunt mollit anim id est laborum</p>
                        </div>
                    </div>
                </div><!-- End Service Item -->

                <div class="col-md-6" >
                    <div class="service-item d-flex position-relative h-100">
                        <i class="bi bi-brightness-high icon flex-shrink-0"></i>
                        <div>
                            <h4 class="title"><a href="service-details.html" class="stretched-link">Nemo Enim</a></h4>
                            <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui
                                blanditiis praesentium voluptatum deleniti atque</p>
                        </div>
                    </div>
                </div><!-- End Service Item -->

                <div class="col-md-6" >
                    <div class="service-item d-flex position-relative h-100">
                        <i class="bi bi-calendar4-week icon flex-shrink-0"></i>
                        <div>
                            <h4 class="title"><a href="service-details.html" class="stretched-link">Eiusmod Tempor</a>
                            </h4>
                            <p class="description">Et harum quidem rerum facilis est et expedita distinctio. Nam libero
                                tempore, cum soluta nobis est eligendi</p>
                        </div>
                    </div>
                </div><!-- End Service Item -->

            </div>

        </div>

    </section><!-- /Services Section -->
{% endif %}